name = "scienest"
compatibility_date = "2023-05-08"

[[ d1_databases ]]
binding = "DB"
database_name = "scienest"
database_id = "f349fbf4-5838-482c-beec-706115dc80a7"
preview_database_id = "f349fbf4-5838-482c-beec-706115dc80a7"
