name = "scienest"
compatibility_date = "2023-01-14"

[[ d1_databases ]]
binding = "DB"
database_name = "scienest"
database_id = "e08f419b-bde8-4d57-95d0-7bd3b395be61"
preview_database_id = "e08f419b-bde8-4d57-95d0-7bd3b395be61"
